repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use latest Black version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use latest Flake8 version
    hooks:
      - id: flake8
